name: Jobs and Steps

on:
    push:
        branches: [ main]
    workflow_dispatch:

jobs:

    test:
      name: Run Tests
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Simulate running tests
          run: |
            echo "Running tests suite"
            sleep 3
            echo "Test 1: User login"
            echo "Test 2: Data fetch"
            echo "Test 3: Submitting the form"
            echo "All tests passed successfully"

    lint:
        name: Run linting
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Simulate linting
              run: |
                echo "Checking code"
                sleep 2
                echo "No style error found"
    

    report:
        name: Generate Report
        runs-on: ubuntu-latest
        needs: [ test, lint]

        steps:
            - name: Print Final report
              run: |
                echo "Pipeline Completed"
                echo "All tests passed and code is clean"

