name: Matrix Build - Multi Dimensional

on:
    workflow_dispatch:

jobs:
    test:
        name: Test (${{matrix.os }} / v${{ matrix.version }})
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest]
                version: [18,20]

                exclude:
                    - os: windows-latest
                      version: 18
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Print current matrix combination
              run: echo "Running on ${{ matrix.os }} with version ${{ matrix.version }}"
              
            - name: Show OS-Specific info
              run: |
                echo "Runner OS : ${{ runner.os }}"
                echo "Version : ${{ matrix.version }}"

            - name: Simulate tests
              run: |
                echo "All tests passed on ${{ matrix.os }} / v${{ matrix.version }}"


